services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VERSION: ${VERSION}
      BOT_TOKEN: ${BOT_TOKEN}
      ENVIRONMENT: ${ENVIRONMENT}
      API_HOST: ${API_HOST}
      API_SECRET: ${API_SECRET}
      KINOPOISK_API_TOKEN: ${KINOPOISK_API_TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg-data-bot:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  pg-data-bot: