filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/bot.log
    json.keys_under_root: true  # Разворачивает JSON в корневые поля
    json.add_error_key: true     # Добавляет поле ошибки, если что-то не так
    fields:
      service: bot

output.logstash:
  hosts: ["logstash:5044"]
