name: Deploy to Server

on:
  push:
    branches:
      - deploy

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Project Files
      - name: Checkout Project Files
        uses: actions/checkout@v3

      # 2. Configure SSH Access
      - name: Configure SSH Access
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Set VERSION and Create Tag
      - name: Set VERSION and Create Tag
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          
          git tag -a "v${VERSION}" -m "Release version ${VERSION}"
          git push origin "v${VERSION}"

      # 4. Upload Project to Server
      - name: Upload Project to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            mkdir -p /home/${{ secrets.SSH_USER }}/watchlist-bot
          EOF
          
          scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/watchlist-bot
          
      # 5. Deploy Application with Docker Compose
      - name: Deploy Application with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=5 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/${{ secrets.SSH_USER }}/watchlist-bot
            
            # Setting a unique project name
            export COMPOSE_PROJECT_NAME=watchlist-bot
          
            export VERSION=${{ env.VERSION }}
            export ENVIRONMENT=${{ secrets.ENVIRONMENT }}
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}  
            export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            export POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}  
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export LOCALES_DIR=${{ secrets.LOCALES_DIR }}
            export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            export ROOT_TELEGRAM_ID = ${{ secrets.ROOT_TELEGRAM_ID }}
            export MASTER_KEY = ${{ secrets.MASTER_KEY }}
            export API_HOST=${{ secrets.API_HOST }}  
            export API_SECRET=${{ secrets.API_SECRET }}
            export YOUTUBE_API_TOKEN = ${{ secrets.YOUTUBE_API_TOKEN }}
            export IMDB_API_TOKEN = ${{ secrets.IMDB_API_TOKEN }}
          
            if [[ "${{ secrets.FULL_REBUILD }}" == "true" ]]; then
              docker-compose down --rmi all
              docker-compose build --no-cache
            else
              docker-compose build
            fi
          
            docker-compose up -d
          EOF
